[build]
  publish = "dist"  # Adjust this if your build folder is named differently
  command = "npm run build"  # Command to build your project (assuming you're using npm)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

# Optional caching settings for assets like particles.js and particles.json
[[headers]]
  for = "/particles.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/particles.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

